exports.SOCKETS = {
    SEND_MESSAGE: "SEND_MESSAGE",
    GET_MESSAGE: "GET_MESSAGE",
    REGISTRATION: "REGISTRATION",
    LOGIN: "LOGIN",
    LOGOUT: "LOGOUT",
    UPDATE_PASSWORD: "UPDATE_PASSWORD",
    SET_GAMER_ROLE: "SET_GAMER_ROLE",
    GET_LOBBY: "GET_LOBBY",
    SUICIDE: "SUICIDE",
    GET_USER_INFO: "GET_USER_INFO",
    GET_SCENE: "GET_SCENE",
    MOTION: "MOTION",
    FIRE: "FIRE",
    ERROR: "ERROR",
    TOKEN_VERIFICATION: "TOKEN_VERIFICATION",
};

exports.MEDIATOR = {
    TRIGGERS: {
        GET_USER: "GET_USER",
        ALL_USERS: "ALL_USERS",
        GAME_TANKS: "GAME_TANKS",
    },
};

exports.updateSceneTimestamp = 16;
